name: wordle-helper
region: nyc

domains:
- domain: wordle-helper.pddyrdbrd.net
  type: PRIMARY

static_sites:
  - name: wordle-helper-web
    github:
      repo: paddyredbeard/wordle-helper
      branch: main
      deploy_on_push: true
    build_command: pnpm run build
    output_dir: dist
    environment_slug: node-js
    routes:
      - path: /

